install.packages("pacman") # Install the package for managing other packages
library(pacman) # load the "package manage" package in the current session
p_load("recommenderlab") # install load the reqired package(s)


data(Jester5k) # load the jokes data from the recommenderlab library

Jester5k # see the datatype
# 5000 x 100 rating matrix of class 'realRatingMatrix' with 362106 ratings.

set.seed(111) # for reproducability of the results 

# We can get all the ratings from this 'realRatingMatrix' Jester5k through the command "getRatings" 

# Inspecting the max and min in the data
# Check max rating by any user for any joke
max(getRatings(Jester5k)) #  9.9
# Check max rating by any user for any joke
min(getRatings(Jester5k)) # -9.95

###########----- Inspecting rating pattern of a user -----################ 
# Check the ratings by any given user 
rowCounts(Jester5k[1,]) 
# u2841 - 81,  User u2841 first row has rated 81 jokes 

as(Jester5k[1,], "list") # to see the jokes rated by user2841
# u2841's rating for joke 1 is "7.91"

rowMeans(Jester5k[1,]) # Average of all rating for this user is 3.855185  
########################################################################

######################### Inspecting Data Summary ###############################################
# If we use the ratings as provided by the user, the model be have row bias, which is an individual's
# tendency to rate every joke very high or very low
# To remove the row bias, we can normalize the ratings - There are many options for normalization 
# such as row centering (difference from the row mean) or Z-score normalization 

# Below we show the the distribution of the non-normalized and normalized ratings
hist(getRatings(Jester5k), breaks=50)
hist(getRatings(normalize(Jester5k)), breaks=50) # we normalize Jester5k and then get all the ratings form it

hist(rowCounts(Jester5k), breaks = 50) # distribution of # of number of jokes rated by a user

hist(colMeans(Jester5k), breaks = 50) # distribution of average ratings per joke
#################################################################################################


# Evaluation Scheme - We need to define an evaluation scheme to make predictions. This evaluation scheme creates train, test data internally for 
# latter usage
eval <- evaluationScheme(Jester5k[1:2000], method="split", train=0.9, given=15, goodRating=5) # we will use only 2000 users 

# Split the data into a train set of 90% and 10% of test(holdout) set 
# For the test set 15 jokes will be given to the recommender algorithm and the other jokes will 
# be held out for computing the error. The 15 jokes are used to find users from the train set who are similar 
# to the users from the test set for whom we are evaluating our predictions. 
# Good rating is the cutoff value of rating above which wewould predict the user to like the joke

eval # We will use this training the model and evaluating the model's performance

############################## Building the Recommender System ##################################
# A recommender is created using the creator function Recommender() 


# Here "known" are the 15 jokes rating we had given for test users to find similar users from the train set 

r_ubcf <- Recommender(getData(eval, "train"), "UBCF") # Recommendation Model generated by user-based collaboration filterting method 
pred_ubcf <- predict(r_ubcf, getData(eval, "known"), type="ratingMatrix") # predictions based on UBCF | Predict returns predicted ratings on test data
as(pred_ubcf, "matrix")[1:10,1:10] # Check the predicted ratings of 10 users for first 10 jokes.

r_ibcf <- Recommender(getData(eval, "train"), "IBCF") # Recommendation Model generated by item-based collaboration filterting method  
pred_ibcf <- predict(r_ibcf, getData(eval, "known"), type="ratingMatrix") # predictions based on IBCF | Predict returns predicted ratings on test data
as(pred_ibcf, "matrix")[1:10,1:10]# Check the predicted ratings of 10 users for first 10 jokes.


# Assesing prediction accurcay of the three models 
error <- rbind( UBCF = calcPredictionAccuracy(pred_ubcf, getData(eval, "unknown")), # "unkown" are the heldout ratings in the test set 
                IBCF = calcPredictionAccuracy(pred_ibcf, getData(eval, "unknown")))
error
# unknown is the jokes not used in making predictions for test data

# We see that User based collaboration filtering achieves higher prediction accuracy than the item based prediction accuracy. 
#####################################################-------END-------#########################################################


################# Getting the Student rating and predictign their ratings for the jokes they have not read ########################
# For making predictions for a new user, the algorithm requires the user to be used in the model. 
# Thus, we would add the student's rating into the jester dataset (of type realratingmatrix, an object the algorithm uses)
# first convert the jester5k data into a normal matrix for binding the student provided rating matrix to it
jester_mat <- as(Jester5k[1:2000], "matrix") # converted to normal martix
class(jester_mat) # "matrix"

# create an empty matrix to be filled by student's rating 
my_ratings <- matrix(NA,nrow=1, ncol=100)
rownames(my_ratings) <- readline(prompt = "My name is:") # set rowname to the student's name 

# Now we will rate 15 jokes  
for (i in 1:15){
  print(paste0("read joke"," ", i))
  my_ratings[1,i] = as.numeric(readline(prompt = "Please type your rating for this joke:"))
}

Jester_mat_1 <- rbind(jester_mat,my_ratings) # add my ratings to the overall rating dataset

jester <- as(Jester_mat_1, "realRatingMatrix") # convert back this to the object class recommenderlab library uses
class(jester) # "realRatingMatrix"

# Define eveulation scheme. Here we need to keep given < the jokes you have rated, thus keeping it 6
eval <- evaluationScheme(jester, method="split", train=0.9, given=6, goodRating=5)


r_ubcf <- Recommender(getData(eval, "train"), "UBCF") # Recommendation Model generated by user-based collaboration filterting method 
pred_ubcf <- predict(r_ubcf,jester , type="ratingMatrix") # predictions based on UBCF | Predict returns predicted ratings on whole data
as(pred_ubcf, "matrix")[2001,] # see predictions for other jokes for you, you were the 2001st user


##########################################-----END----#####################################################################

